#
# GNUmakefile for target TestFrameworkTool
# begin - generated by buildtool
#

include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME= TestFrameworkTool

TestFrameworkTool_OBJC_FILES = TestFrameworkTool/main.m 

TestFrameworkTool_C_FILES = 

TestFrameworkTool_CPP_FILES = 

TestFrameworkTool_OBJCPP_FILES = 

TestFrameworkTool_HEADER_FILES = 

TestFrameworkTool_RESOURCE_FILES = 

ADDITIONAL_INCLUDE_DIRS += -I. \
	-I./TestFrameworkTool 

ADDITIONAL_OBJC_LIBS += 

include $(GNUSTEP_MAKEFILES)/common.make
include $(GNUSTEP_MAKEFILES)/tool.make

#
# end - generated makefile
#
